FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

COPY . ./

RUN dotnet restore

WORKDIR /app

RUN dotnet built -c Release -o /app/build
RUN dotnet publish --no-restore -c Release -o app/publish

FROM build AS publish
FROM base AS final
WORKDIR /app

COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet","Api-Gateway.dll"]