# version: '3'
# services:
#   basket-service:
#     image: basketservice
#     ports:
#       - "4000:80"
#     restart: always
#     version: '3'

services:
  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: redis-server --requirepass RRnFPZ93tjBHB9W62p

volumes:
  redis_data: