# version: '3'
# services:
#   basket-service:
#     image: basketservice
#     ports:
#       - "4000:80"
#     restart: always
#     version: '3'

services:
  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: redis-server --requirepass RRnFPZ93tjBHB9W62p
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  redis_data:
