# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "backend" ]

jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore AuthService Dependencies
      working-directory: ./Services/Identity
      run: dotnet restore
    - name: Restore Inventory Dependencies
      working-directory:  ./Services/Inventory.Api
      run: dotnet restore
    - name: Restore Basket dependencies
      working-directory:  ./Services/Basket
      run: dotnet restore
    - name: Restore NotificationService dependencies 
      working-directory:  ./Services/NotificationService
      run: dotnet restore
  
  build:
   needs: restore
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Build AuthService 
      working-directory: ./Services/Identity
      run: dotnet build
    - name: Build InventoryService 
      working-directory:  ./Services/Inventory.Api
      run: dotnet build
    - name: Build BasketService
      working-directory:  ./Services/Basket
      run: dotnet build
    - name: Build NotificationService 
      working-directory:  ./Services/NotificationService
      run: dotnet build
  
  # test:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #   - name: Setup .NET 6
  #     uses: actions/setup-dotnet@v1
  #     with:
  #       dotnet-version: '6.0.x'
  #   - name: Restore dependencies
  #     run: dotnet restore
  #   - name: Test
  #     run: dotnet test --no-build --verbosity normal --no-restore
